#!/usr/bin/env python3
"""Derive the published ABI catalog (apps/abi/) from the frozen deployment bundle.

Input authority: deployments/monad-testnet/abi/ (generated by export_deployed_abis.py
from pinned qualified sources). Every input ABI is hash-revalidated before copying, so
the catalog can never drift from the frozen bundle it was derived from.

Emits apps/abi/<Contract>.json (byte-identical), apps/abi/abi.ts (generated barrel),
and apps/abi/manifest.json (catalog schema v2 with ownership, coverage and explorer
verification status). Does not compile, does not touch frozen outputs.
"""
import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUNDLE = ROOT / 'deployments/monad-testnet/abi'
CATALOG = ROOT / 'apps/abi'

# Ownership classification for every contract in the bundle. Roles come from the
# bundle manifest; a contract file shared by several roles is listed once.
OWNERSHIP = {
    'RetroPickQuoteAssetRegistryV2': 'RETROPICK_OWNED',
    'RetroPickFeeEscrowV2': 'RETROPICK_OWNED',
    'RetroPickHookDeployerV2': 'RETROPICK_OWNED',
    'RetroPickMemeHookV2': 'RETROPICK_OWNED',
    'RetroPickBuybackVaultV2': 'RETROPICK_OWNED',
    'RetroPickLaunchLockerV2': 'RETROPICK_OWNED',
    'KuruEnvironmentV2': 'RETROPICK_OWNED',
    'GraduationCoordinatorV2': 'RETROPICK_OWNED',
    'KuruGraduationExecutorV2': 'RETROPICK_OWNED',
    'UniswapV4GraduationExecutorV2': 'RETROPICK_OWNED',
    'RetroPickLaunchFactoryV2': 'RETROPICK_OWNED',
    'RetroPickLaunchDeployerV2': 'RETROPICK_OWNED',
    'ExecutorDonationLockV2': 'RETROPICK_OWNED',
    'RetroPickGraduationGuardV2': 'RETROPICK_OWNED',
    'RetroPickLauncherTokenV2': 'RETROPICK_OWNED',
    'RetroPickBondingCurveV2': 'RETROPICK_OWNED',
    'KuruLiquidityLockV2': 'RETROPICK_OWNED',
    'WETH': 'UPSTREAM_UNISWAP_V4_STACK',
    'Permit2': 'UPSTREAM_UNISWAP_V4_STACK',
    'PoolManager': 'UPSTREAM_UNISWAP_V4_STACK',
    'PositionDescriptor': 'UPSTREAM_UNISWAP_V4_STACK',
    'PositionManager': 'UPSTREAM_UNISWAP_V4_STACK',
    'Router': 'UPSTREAM_KURU',
    'MarginAccount': 'UPSTREAM_KURU',
    'OrderBook': 'UPSTREAM_KURU',
    'KuruAMMVault': 'UPSTREAM_KURU',
    'ERC20MetadataInterface': 'EXTERNAL_INTERFACE_ONLY',
}

# Sourcify verification snapshot, recorded 2026-10-09 (see
# evidence/launchpad/v2-monad-testnet/source-verification-foundry.md). RetroPick-owned
# contracts: runtime exact_match on both the mandated BlockVision Sourcify endpoint
# and the public Sourcify repository. Upstream/external contracts were NOT submitted;
# they are not RetroPick-owned source.
VERIFICATION_RECORDED_AT = '2026-10-09T17:10:00Z'
VERIFICATION = {name: {'sourcifyRuntimeMatch': 'exact_match',
                       'endpoints': ['https://sourcify-api-monad.blockvision.org/',
                                     'https://sourcify.dev/server/']}
                for name, owner in OWNERSHIP.items() if owner == 'RETROPICK_OWNED'}

# TS barrel export name per contract file.
EXPORT_NAMES = {
    'RetroPickLaunchFactoryV2': 'retroPickLaunchFactoryV2Abi',
    'GraduationCoordinatorV2': 'graduationCoordinatorV2Abi',
    'RetroPickBondingCurveV2': 'retroPickBondingCurveV2Abi',
    'RetroPickLauncherTokenV2': 'retroPickLauncherTokenV2Abi',
    'RetroPickLaunchDeployerV2': 'retroPickLaunchDeployerV2Abi',
    'RetroPickQuoteAssetRegistryV2': 'retroPickQuoteAssetRegistryV2Abi',
    'RetroPickFeeEscrowV2': 'retroPickFeeEscrowV2Abi',
    'RetroPickBuybackVaultV2': 'retroPickBuybackVaultV2Abi',
    'KuruGraduationExecutorV2': 'kuruGraduationExecutorV2Abi',
    'KuruEnvironmentV2': 'kuruEnvironmentV2Abi',
    'KuruLiquidityLockV2': 'kuruLiquidityLockV2Abi',
    'RetroPickLaunchLockerV2': 'retroPickLaunchLockerV2Abi',
    'RetroPickHookDeployerV2': 'retroPickHookDeployerV2Abi',
    'RetroPickMemeHookV2': 'retroPickMemeHookV2Abi',
    'UniswapV4GraduationExecutorV2': 'uniswapV4GraduationExecutorV2Abi',
    'RetroPickGraduationGuardV2': 'retroPickGraduationGuardV2Abi',
    'ExecutorDonationLockV2': 'executorDonationLockV2Abi',
    'WETH': 'wethAbi',
    'Permit2': 'permit2Abi',
    'PoolManager': 'poolManagerAbi',
    'PositionDescriptor': 'positionDescriptorAbi',
    'PositionManager': 'positionManagerAbi',
    'Router': 'kuruRouterAbi',
    'MarginAccount': 'kuruMarginAccountAbi',
    'OrderBook': 'kuruOrderBookAbi',
    'KuruAMMVault': 'kuruAmmVaultAbi',
    'ERC20MetadataInterface': 'erc20MetadataInterfaceAbi',
}


def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def export():
    bundle_manifest = json.loads((BUNDLE / 'manifest.json').read_text())
    by_name = {}
    for contract in bundle_manifest['contracts']:
        entry = dict(contract)
        existing = by_name.get(entry['contractName'])
        if existing is None:
            role = entry.pop('role')
            entry['deployments'] = [{'role': role, 'address': entry['address']}]
            by_name[entry['contractName']] = entry
        else:
            role = entry.pop('role')
            existing['deployments'].append({'role': role, 'address': entry['address']})

    CATALOG.mkdir(parents=True, exist_ok=True)
    for stale in CATALOG.glob('*.json'):
        if stale.name not in ('manifest.json',):
            stale.unlink()

    catalog_contracts = []
    files = {}
    for name, entry in sorted(by_name.items()):
        source_file = BUNDLE / entry['abi']
        abi = json.loads(source_file.read_text())
        assert isinstance(abi, list) and abi, name
        # Revalidate the frozen bundle hash before deriving from it.
        assert entry['abiSHA256'] == sha256_file(source_file), f'Bundle hash drift: {name}'
        target_file = CATALOG / (name + '.json')
        shutil.copyfile(source_file, target_file)
        assert sha256_file(target_file) == entry['abiSHA256']
        files[name] = entry['abiSHA256']
        catalog_contracts.append({
            'contractName': name,
            'abiFile': name + '.json',
            'abiSHA256': entry['abiSHA256'],
            'roles': sorted({d['role'] for d in entry['deployments']}),
            'address': entry['deployments'][0]['address'],
            'deployments': entry['deployments'],
            'dynamicInstances': bool(bundle_manifest.get('templates', {}).get(
                next((d['role'].removeprefix('demo.') for d in entry['deployments'] if d['role'].startswith('demo.')), ''))) or None,
            'coverage': entry['coverage'],
            'ownership': OWNERSHIP[name],
            'origin': entry.get('origin'),
            'compiler': entry.get('compiler'),
            'functions': entry.get('functions'),
            'events': entry.get('events'),
            'errors': entry.get('errors'),
            'verification': VERIFICATION.get(name) or {
                'status': 'NOT_SUBMITTED',
                'reason': 'Third-party owned source; not published as RetroPick-owned.',
            },
        })
        catalog_contracts[-1] = {k: v for k, v in catalog_contracts[-1].items() if v is not None}

    manifest = {
        'schemaVersion': 2,
        'catalog': 'retropick-v2-monad-testnet',
        'description': 'Published JSON ABI catalog derived from the frozen deployment bundle.',
        'chainId': bundle_manifest['chainId'],
        'deploymentBlock': bundle_manifest['deploymentBlock'],
        'deployedSourceSHA': bundle_manifest['deployedSourceSHA'],
        'kuruSDKSourceSHA': bundle_manifest.get('kuruSDKSourceSHA'),
        'kuruContractsSourceSHA': bundle_manifest.get('kuruContractsSourceSHA'),
        'derivedFrom': {
            'bundle': 'deployments/monad-testnet/abi/',
            'bundleManifestSHA256': sha256_file(BUNDLE / 'manifest.json'),
            'limitations': bundle_manifest.get('limitations'),
        },
        'verification': {
            'recordedAt': VERIFICATION_RECORDED_AT,
            'evidence': 'evidence/launchpad/v2-monad-testnet/source-verification-foundry.md',
            'sourcifyEndpoints': VERIFICATION[list(VERIFICATION)[0]]['endpoints'] if VERIFICATION else [],
            'note': 'exact_match = runtime bytecode identity confirmed by Sourcify recompilation.',
        },
        'templates': bundle_manifest.get('templates', {}),
        'contracts': catalog_contracts,
        'generatedAt': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    }
    (CATALOG / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')

    # Generated TS barrel so bundler-resolution consumers need no resolveJsonModule.
    lines = [
        '// GENERATED by scripts/launchpad/export_abi_catalog.py — do not edit.',
        f'// Derived from deployments/monad-testnet/abi/ (deployed source {bundle_manifest["deployedSourceSHA"]}).',
        '// Each export is the complete artifact ABI from the JSON file of the same contract.',
    ]
    for name, symbol in EXPORT_NAMES.items():
        if name not in files:
            continue
        abi = json.loads((CATALOG / (name + '.json')).read_text())
        lines.append('export const ' + symbol + ' = ' + json.dumps(abi, separators=(',', ':')) + ' as const;')
    (CATALOG / 'abi.ts').write_text('\n\n'.join(lines) + '\n')

    summary = {'abiFiles': len(files), 'owned': sum(1 for c in catalog_contracts if c['ownership'] == 'RETROPICK_OWNED'),
               'upstream': sum(1 for c in catalog_contracts if c['ownership'].startswith('UPSTREAM')),
               'external': sum(1 for c in catalog_contracts if c['ownership'].startswith('EXTERNAL'))}
    print(json.dumps(summary))
    return manifest


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    export()
