"""Generate/check Solidity vectors against the existing exact Python oracle."""
import argparse
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "research/integration/kuru"))
from completion_terminal_quote import CurveCompletionState, completion_terminal_quote

rng = random.Random(10143)
rows = []
for decimals in (6, 18):
    unit = 10 ** decimals
    for i in range(40):
        phantom = unit * rng.randint(1, 100)
        real = unit * rng.randint(0, 200)
        tokens = 10 ** 18 * rng.randint(1000, 1000000)
        reserved = tokens // rng.randint(2, 10)
        if i == 0:
            tokens = reserved
        fee, tax = rng.randint(0, 1000), rng.randint(0, 1000)
        fee_bucket, tax_bucket = rng.randint(0, unit), rng.randint(0, unit)
        state = CurveCompletionState(phantom, real + fee_bucket + tax_bucket,
                                    fee_bucket, tax_bucket, tokens, reserved, fee, tax)
        result = completion_terminal_quote(state)
        fields = ", ".join(str(x) for x in state.__dict__.values())
        rows.append(f"        _check(CompletionQuoteMathV2.State({fields}), {result.terminal_real_quote}, {result.gross_quote_in});")
output = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;
// Generated by test/v2/tools/generate_completion_vectors.py; values come from the research Python oracle.
import {Test} from "forge-std/Test.sol";
import {CompletionQuoteMathV2} from "../../../src/v2/libraries/CompletionQuoteMathV2.sol";
contract CompletionQuoteOracleV2Test is Test {
    function testDifferentialPythonOracle80States() public pure {
""" + "\n".join(rows) + """
    }
    function _check(CompletionQuoteMathV2.State memory s, uint256 terminal, uint256 gross) private pure {
        (uint256 actualTerminal, uint256 actualGross) = CompletionQuoteMathV2.calculate(s);
        assertEq(actualTerminal, terminal);
        assertEq(actualGross, gross);
    }
}
"""
target = ROOT / "contracts/test/v2/unit/CompletionQuoteOracleV2.t.sol"
if "--check" in sys.argv:
    assert target.read_text() == output, "oracle vectors differ; regenerate"
else:
    target.write_text(output)
