/** Prices (including compatibility priceRaw and candle OHLC) are human quote/token × 1e18.
 * Token/quote amounts and market caps retain their asset's atomic units. */
export type IndexFreshness = { chainId: 10143; indexedBlock: number; headBlock: number; confirmations: number; lagBlocks: number; indexedAt: string | null; syncing: boolean; error: string | null; source: 'MONAD_EVENT_INDEXER'; indexedBlockHash?: string; reorgRevision?: number; projectionVersion?: number; beneficiaryIndexedBlock?: number };
export type IndexedTrade = { id: string; token: string; venue: 'CURVE' | 'KURU'; side: 'buy' | 'sell'; actor: string; maker?: string; quoteRaw: string; executionQuoteRaw?: string; tokensRaw: string; priceRaw: string; priceX18?: string; feeRaw: string | null; block: number; blockHash?: string; timestamp: number; transactionHash: string; transactionIndex?: number; logIndex: number; orderId?: string };
export type IndexedCandle = { timestamp: number; open: string; high: string; low: string; close: string; quoteVolumeRaw: string; tradeCount: number };
export type IndexedMarketParameters = { pricePrecision: string; sizePrecision: string; baseDecimals: number; quoteDecimals: number; baseAsset: string; quoteAsset: string };
export type IndexedLaunch = { token: string; curve: string; creator: string; quoteAsset: string; quoteSymbol: string; quoteDecimals: number; baseDecimals?: number; name: string; symbol: string; description: string; logo: string; socials?: { twitter: string; telegram: string; discord: string; website: string; farcaster: string }; supplyRaw: string; launchSupplyRaw?: string; createdBlock: number; createdAt: string; phase: 'ACTIVE' | 'GRADUATION_READY' | 'GRADUATING' | 'GRADUATED'; venue: 'KURU' | 'UNISWAP_V4'; market: string | null; vault: string | null; lpLock: string | null; policyVersion: number; quoteReserveRaw: string; liquidityRaw?: string | null; liquiditySource?: 'CURVE_RESERVE' | 'UNAVAILABLE'; priceRaw: string | null; priceX18?: string | null; priceSource?: 'CURVE_SPOT' | 'KURU_LAST_TRADE' | 'UNAVAILABLE'; marketCapRaw: string | null; bondingProgressBps: number; volume24hRaw: string; lifetimeVolumeRaw: string; trades24h: number; holderCount: number; change24hBps: string | null; candles: IndexedCandle[]; marketParams?: IndexedMarketParameters; graduationBlock?: number; graduationTimestamp?: number; launchTransactionHash?: string; graduationTransactionHash?: string };
export type IndexedOrder = { market: string; token: string; orderId: string; owner: string; side: 'buy' | 'sell'; priceUnits: string; priceX18: string; originalSizeUnits: string; remainingSizeUnits: string; baseDecimals: number; sizePrecision: string; createdAt: number; createdBlock: number; status: 'OPEN' | 'PARTIALLY_FILLED' | 'FILLED' | 'CANCELLED'; transactionHash: string };
export type IndexedAssetMetadata = { token: string; name: string; symbol: string; decimals: number | null };
export type IndexedWalletAsset = IndexedAssetMetadata & { sources: ('wallet' | 'margin' | 'escrow')[]; quoteAsset: string | null; quoteSymbol: string | null; quoteDecimals: number | null };
export type IndexedClaim = { id: string; wallet: string; token: string; amountRaw: string; block: number; timestamp: number; transactionHash: string; logIndex: number };
export type IndexedBuyback = { token: string; symbol: string; decimals: number; creatorRecipient: string; protocolRecipient: string; protocolFeeShareBps: number };
export type IndexedHolder = { address: string; balanceRaw: string; rank?: number; supplyBps?: string; role?: 'CURVE' | 'COORDINATOR' | 'LP_EXCESS_LOCK' | 'KURU_INFRASTRUCTURE' | 'BUYBACK_VAULT' | 'FEE_ESCROW' | 'WALLET' };
export type IndexedQualifyingEvent = { id: string; chainId: 10143; blockNumber: number; blockHash: string; txHash: string; logIndex: number; transactionIndex: number; timestamp: number; eventName: 'TokenLaunched' | 'CurveBuy' | 'CurveSell' | 'KuruTrade'; actor: string; token: string; quote: string; quoteAmountRaw: string };
export type IndexedActivityPage = { events: IndexedQualifyingEvent[]; nextCursor: string | null; canonicalFromBlock: number; canonicalToBlock: number };
export type IndexEnvelope<T> = { data: T; freshness: IndexFreshness; nextCursor?: string | null; sortGrouping?: 'QUOTE_ASSET'; resolution?: CandleResolution; range?: CandleRange };
export type CandleResolution = '1m' | '5m' | '15m' | '1h';
export type CandleRange = '1h' | '6h' | '24h' | '7d' | '30d' | 'all';
