import {createPublicClient,http,decodeEventLog,zeroAddress,type Address,type Hex} from 'viem';
import {addresses,monad,type ChainClient} from '@retropick/launchpad-sdk/chain';
import {factoryAbi,coordinatorAbi,tokenAbi,curveAbi,registryAbi} from '@retropick/launchpad-sdk/abi';
import {indexerAbi} from '@retropick/launchpad-sdk/events';
import type {IndexedLaunch} from '@retropick/launchpad-sdk/read-model';
import {Store,type JournalEvent} from './store.ts';
import {project,type LaunchSeed} from './project.ts';
export const START_BLOCK=69509526;
const rootNames=new Set(['TokenLaunched','LaunchCommitted','GraduationSecured','GraduationCompleted']);
export class Indexer {
 store:Store;client:ChainClient;confirmations:number;head=0;syncing=false;error:string|null=null;headers=new Map<number,{hash:Hex;timestamp:number}>();
 constructor(store:Store,url:string,confirmations=8){this.store=store;this.confirmations=confirmations;let due=0;const fetchFn:typeof fetch=async(input,init)=>{const wait=Math.max(0,due-Date.now());due=Math.max(due,Date.now())+130;if(wait)await new Promise(r=>setTimeout(r,wait));return fetch(input,init);};this.client=createPublicClient({chain:monad,batch:{multicall:{batchSize:4096,wait:25}},transport:http(url,{fetchFn,retryCount:3,retryDelay:500})}) as ChainClient;}
 async header(block:number,fresh=false){if(!fresh&&this.headers.has(block))return this.headers.get(block)!;const value=await this.client.getBlock({blockNumber:BigInt(block)});if(!value.hash)throw Error('Missing block hash');const result={hash:value.hash,timestamp:Number(value.timestamp)};if(!fresh)this.headers.set(block,result);return result;}
 async reconcile(stage:string){for(const checkpoint of this.store.checkpoints(stage)){if((await this.header(checkpoint.block,true)).hash.toLowerCase()===checkpoint.hash.toLowerCase())return;const remaining=this.store.checkpoints(stage).filter(c=>c.block<checkpoint.block);let common=START_BLOCK-1;for(const c of remaining){if((await this.header(c.block,true)).hash.toLowerCase()===c.hash.toLowerCase()){common=c.block;break;}}this.store.rollback(common);this.headers.clear();console.log('Reorg rollback:',common);return;}}
 async scan(stage:string,target:number,contracts:Address[],start=START_BLOCK){if(!contracts.length)return;const names=stage==='root'?rootNames:new Set(indexerAbi.map(e=>e.name).filter(n=>!rootNames.has(n)));const eventsAbi=indexerAbi.filter(e=>names.has(e.name));let from=Math.max(start,this.store.cursor(stage,start)+1);while(from<=target){const to=Math.min(from+99,target);const logs=await this.client.getLogs({address:contracts,events:eventsAbi,fromBlock:BigInt(from),toBlock:BigInt(to)} as Parameters<ChainClient['getLogs']>[0]);const events:JournalEvent[]=[];for(const log of logs){if(log.removed||!log.blockHash||!log.transactionHash||log.blockNumber===null||log.logIndex===null||log.transactionIndex===null)throw Error('Incomplete event');let decoded;try{decoded=decodeEventLog({abi:indexerAbi,data:log.data,topics:log.topics});}catch{throw Error('Source ABI/event mismatch');}const header=await this.header(Number(log.blockNumber));if(header.hash.toLowerCase()!==log.blockHash.toLowerCase())throw Error('Log block mismatch');events.push({id:`10143:${log.blockHash}:${log.transactionHash}:${log.logIndex}`,chainId:10143,address:log.address.toLowerCase(),name:decoded.eventName,args:decoded.args as Record<string,unknown>,block:Number(log.blockNumber),blockHash:log.blockHash,transactionHash:log.transactionHash,transactionIndex:log.transactionIndex,logIndex:log.logIndex,timestamp:header.timestamp});}const header=await this.header(to);this.store.commit(stage,to,header.hash,events);if(events.length||to===target||(to-START_BLOCK)%5000<100)console.log('Indexed',stage,to,'/',target,'events',events.length);from=to+1;}}
 async discover(target:number){const events=this.store.events('root');const launches=events.filter(e=>e.name==='TokenLaunched');const seeds:LaunchSeed[]=[];for(const event of launches){const token=String(event.args.token) as Address;const curve=String(event.args.curve) as Address;const blockNumber=BigInt(target);
  const [packet,ledger,receipt,name,symbol,supply,description,logo,remaining,reserved,quote,reserves]=await Promise.all([
   this.client.readContract({address:addresses.coordinator,abi:coordinatorAbi,functionName:'packet',args:[token],blockNumber}),this.client.readContract({address:addresses.coordinator,abi:coordinatorAbi,functionName:'ledger',args:[token],blockNumber}),this.client.readContract({address:addresses.coordinator,abi:coordinatorAbi,functionName:'receipt',args:[token],blockNumber}),this.client.readContract({address:token,abi:tokenAbi,functionName:'name',blockNumber}),this.client.readContract({address:token,abi:tokenAbi,functionName:'symbol',blockNumber}),this.client.readContract({address:token,abi:tokenAbi,functionName:'totalSupply',blockNumber}),this.client.readContract({address:token,abi:tokenAbi,functionName:'description',blockNumber}),this.client.readContract({address:token,abi:tokenAbi,functionName:'logo',blockNumber}),this.client.readContract({address:curve,abi:curveAbi,functionName:'sellableTokens',blockNumber}),this.client.readContract({address:curve,abi:curveAbi,functionName:'reservedTokens',blockNumber}),this.client.readContract({address:curve,abi:curveAbi,functionName:'realQuoteReserve',blockNumber}),this.client.readContract({address:curve,abi:curveAbi,functionName:'getReserves',blockNumber})]);
  const config=await this.client.readContract({address:addresses.quoteRegistry,abi:registryAbi,functionName:'getConfig',args:[packet.quoteAsset],blockNumber});if(!config.enabled||packet.token.toLowerCase()!==token.toLowerCase()||packet.curve.toLowerCase()!==curve.toLowerCase())throw Error('Launch identity mismatch');
  const phase:IndexedLaunch['phase']=ledger.phase===2?'GRADUATED':ledger.phase===1?'GRADUATING':remaining===0n?'GRADUATION_READY':'ACTIVE';const completed=events.some(e=>e.name==='GraduationCompleted'&&String(e.args.token).toLowerCase()===token.toLowerCase());if((ledger.phase===2)!==completed)throw Error('Coordinator event/state mismatch');
  const allocation=supply-reserved;const zero=zeroAddress.toLowerCase();const price=ledger.phase===2?receipt.seededLaunchTokens>0n?receipt.seededQuote*10n**18n/receipt.seededLaunchTokens:null:reserves[1]>0n?reserves[0]*10n**18n/reserves[1]:null;
  seeds.push({launch:{token:token.toLowerCase(),curve:curve.toLowerCase(),creator:String(event.args.deployer).toLowerCase(),quoteAsset:packet.quoteAsset.toLowerCase(),quoteSymbol:packet.quoteAsset.toLowerCase()===zero?'MON':'USDC',quoteDecimals:config.decimals,name,symbol,description,logo,supplyRaw:supply.toString(),createdBlock:event.block,createdAt:new Date(event.timestamp*1000).toISOString(),phase,venue:packet.venue===1?'KURU':'UNISWAP_V4',market:ledger.phase===2&&receipt.market!==zeroAddress?receipt.market.toLowerCase():null,vault:ledger.phase===2&&receipt.vault!==zeroAddress?receipt.vault.toLowerCase():null,lpLock:ledger.phase===2?ledger.protectedLPReceiver.toLowerCase():null,policyVersion:packet.quotePolicyVersion,quoteReserveRaw:(ledger.phase===2?receipt.seededQuote:quote).toString(),priceRaw:price?.toString()??null,marketCapRaw:price===null?null:(price*supply/10n**18n).toString(),bondingProgressBps:ledger.phase>0?10000:allocation>0n?Number((allocation-remaining)*10000n/allocation):0}});
 }return seeds;}
 async sync(){if(this.syncing)return;this.syncing=true;this.error=null;try{if(await this.client.getChainId()!==10143)throw Error('Wrong chain');this.head=Number(await this.client.getBlockNumber({cacheTime:0}));const target=this.head-this.confirmations;if(target<START_BLOCK)throw Error('Before deployment');await this.reconcile('root');await this.reconcile('dynamic');await this.scan('root',target,[addresses.factory,addresses.coordinator]);const seeds=await this.discover(target);const dynamic=[...new Set(seeds.flatMap(s=>[s.launch.token,s.launch.curve,...(s.launch.market?[s.launch.market]:[])]))] as Address[];if(dynamic.length)await this.scan('dynamic',target,dynamic,Math.min(...seeds.map(s=>s.launch.createdBlock)));const headHeader=await this.header(target,true);if(headHeader.hash!==(await this.header(target)).hash)throw Error('Snapshot reorg');const data=project(this.store.events(),seeds,headHeader.timestamp);this.store.set('snapshot',{...data,indexedBlock:target,indexedAt:new Date().toISOString()});console.log('Synced',target,'launches',data.launches.length,'trades',data.trades.length);}catch(error){this.error='RPC_OR_CHAIN_SYNC_FAILED';console.error('Indexer sync failed; last complete snapshot retained.',error instanceof Error?error.message:error);}finally{this.syncing=false;}}
 freshness(){const snapshot=this.store.get<{indexedBlock:number;indexedAt:string}>('snapshot');const indexedBlock=snapshot?.indexedBlock??START_BLOCK-1;return {chainId:10143 as const,indexedBlock,headBlock:this.head,confirmations:this.confirmations,lagBlocks:Math.max(0,this.head-indexedBlock),indexedAt:snapshot?.indexedAt??null,syncing:this.syncing,error:this.error,source:'MONAD_EVENT_INDEXER' as const};}
}
