'use client';
import {createContext,useContext,useSyncExternalStore,useState,type ReactNode} from 'react';
import {initialPositions} from '@/lib/domain/fixtures';
import type {Position,DemoOrder,Activity} from '@/lib/domain/types';
type DemoContext={connected:boolean;setConnected:(v:boolean)=>void;balance:number;positions:Position[];orders:DemoOrder[];events:Activity[];trade:(p:Position,cost:number)=>void;sell:(marketId:string,side:Position['side'],quantity:number,proceeds:number)=>void;addOrder:(o:DemoOrder)=>void;cancelOrder:(id:string)=>void;redeem:(id:string)=>void;watch:string[];toggleWatch:(id:string)=>void};
const Context=createContext<DemoContext|null>(null);
export function DemoProvider({children}:{children:ReactNode}){const[connected,setConnected]=useState(false),[balance,setBalance]=useState(10000),[positions,setPositions]=useState(initialPositions),[orders,setOrders]=useState<DemoOrder[]>([]),[events,setEvents]=useState<Activity[]>([]);
const stored=useSyncExternalStore(callback=>{window.addEventListener('retropick-watch',callback);window.addEventListener('storage',callback);return()=>{window.removeEventListener('retropick-watch',callback);window.removeEventListener('storage',callback);};},()=>{try{return localStorage.getItem('retropick-watch')||'[]';}catch{return '[]';}},()=> '[]');
let watch:string[]=[];try{const parsed:unknown=JSON.parse(stored);if(Array.isArray(parsed))watch=parsed.filter((x):x is string=>typeof x==='string');}catch{}
const toggleWatch=(id:string)=>{const n=watch.includes(id)?watch.filter(x=>x!==id):[...watch,id];try{localStorage.setItem('retropick-watch',JSON.stringify(n));window.dispatchEvent(new Event('retropick-watch'));}catch{}};
return <Context.Provider value={{connected,setConnected,balance,positions,orders,events,watch,toggleWatch,trade(p,cost){setBalance(b=>b-cost);setPositions(ps=>[p,...ps]);setEvents(e=>[{id:p.id,action:'Buy',marketId:p.marketId,label:p.marketId,amount:p.quantity,value:cost,time:'This demo session'},...e]);},sell(marketId,side,quantity,proceeds){const available=positions.filter(p=>p.marketId===marketId&&p.side===side).reduce((s,p)=>s+p.quantity,0);if(quantity>available||quantity<=0||!Number.isFinite(proceeds))return;let remaining=quantity;setPositions(positions.map(p=>{if(p.marketId!==marketId||p.side!==side||remaining<=0)return p;const take=Math.min(remaining,p.quantity);remaining-=take;return {...p,quantity:p.quantity-take};}).filter(p=>p.quantity>0));setBalance(b=>b+proceeds);setEvents(e=>[{id:'sell-'+Date.now(),action:'Sell',marketId,label:marketId,amount:quantity,value:proceeds,time:'This demo session'},...e]);},addOrder(o){if(o.reservedCash>balance)return;setBalance(b=>b-o.reservedCash);setOrders(x=>[o,...x]);},cancelOrder(id){const order=orders.find(o=>o.id===id);if(!order||order.status!=='OPEN')return;setBalance(b=>b+order.reservedCash);setOrders(x=>x.map(o=>o.id===id?{...o,status:'CANCELLED'}:o));},redeem(id){const p=positions.find(p=>p.id===id);if(p?.state==='REDEEMABLE'&&p.funded&&p.payout){setBalance(b=>b+p.quantity*p.payout!);setPositions(ps=>ps.filter(x=>x.id!==id));setEvents(e=>[{id:'redeem-'+id,action:'Redemption',marketId:p.marketId,label:p.marketId,amount:p.quantity,value:p.quantity*p.payout!,time:'This demo session'},...e]);}}}}>{children}</Context.Provider>}
export const useDemo=()=>{const c=useContext(Context);if(!c)throw new Error('Missing demo provider');return c;};
